package blitz_gui;

import java.util.ArrayList;
import java.util.Random;

/**
 * The abstract class that gives all the wheels base functionality and
 * determines their constants.
 * 
 * @author Taylor Fanel-Luevano
 * @version 1.0
 */
public abstract class Wheel {
    private Random wheelSpin = new Random(); // The seed that is generated for each wheel
    private final int WHEEL_WEIGHT; // The 'weight' of each wheel section
    protected final int WHEEL_COST; // The cost to spin the wheel
    protected ArrayList<Player> playerList; /* The wheel is given a copy of the Player list ptr so 
                                            they can properly perform player-based operations */ 
    
    /**
     * Creates a wheel by setting its weight, cost, and the ptr to the Player list
     * @param wheelWeight - sets WHEEL_WEIGHT
     * @param cost - sets WHEEL_COST
     * @param players - copies the playerlist ptr
     */
    public Wheel(int wheelWeight, int cost, ArrayList<Player> players) {
        WHEEL_WEIGHT = wheelWeight;
        WHEEL_COST = cost;
        playerList = players;
    }

    /**
     * Fetches the cost of the wheel.
     * @return the wheel cost
     */
    public int getCost() {
        return WHEEL_COST;
    }

    /**
     * ...?
     * Why did I think this was necessary? Well, I have
     * no shame, so I'm keeping this here to remind anyone
     * that you don't need to refresh a pointer to a list,
     * okay?
     * @param newList - just...does nothing basically.
     */
    /* public void refreshPlayerList(ArrayList<Player> newList) {
        playerList = newList;
    } */

    /**
     * Charges the selected player based on the cost of the wheel.
     * Can be positive, negative, or 0
     * @param player - the player to charge
     * @param menu - the main menu; used to pass to modCoinCount
     * @see Player#modCoinCount(double, Blitz)
     */
    protected void chargePlayer(Player player, Blitz menu) {
        player.modCoinCount(WHEEL_COST, menu);
    }

    /**
     * Spins the wheel and returns the number generated by
     * wheelSpin, with a min of 1 and a max of the wheel weight
     * @return The number from wheelSpin
     */
    protected int spinWheel() {
        return wheelSpin.nextInt(WHEEL_WEIGHT) + 1;
    }
}
